menu:
    Blog: /
    Archive: /archives/
    Tags: /tag/
    Weibo: http://weibo.com/shenggegege
    GitHub: https://github.com/hentaicracker
    Rss: /atom.xml
    ME: http://hentaicracker.github.io/share/aboutme.html

favicon: /favicon.ico
logo: /blog.png

# Comment
# e.g disqus: seansun
duoshuo: hentaicracker

# Analytics
# google-analytics:
ga: UA-84370929-1

# Copyright Infomation
startyear: 2016
