menu:
    博客: /
    归档: /archives/
    分类: /tag/
    微博: http://weibo.com/shenggegege
    GitHub: https://github.com/hentaicracker
    RSS订阅: /atom.xml
    关于我: http://hentaicracker.github.io/share/aboutme.html

favicon: /favicon.ico
logo: /blog.png

# Comment
# e.g disqus: seansun
duoshuo: hentaicracker

# Analytics
# google-analytics:
ga: UA-84370929-1

# Copyright Infomation
startyear: 2016
